// Characeters are 5x7 blocks
const letterMap = {
    A: ["ssxss",
        "sxsxs",
        "xsssx",
        "xxxxx",
        "xsssx"],
    B: ["xxxxs",
        "xsssx",
        "xxxxs",
        "xsssx",
        "xxxxs"],
    C: ["xxxxx",
        "xssss",
        "xssss",
        "xssss",
        "xxxxx"],
    D: ["xxxxs",
        "xsssx",
        "xsssx",
        "xsssx",
        "xxxxs"],
    E: ["xxxxx",
        "xssss",
        "xxxxs",
        "xssss",
        "xxxxx"],
    F: ["xxxxx",
        "xssss",
        "xxxxs",
        "xssss",
        "xssss"],
    G: ["xxxxx",
        "xssss",
        "xssxx",
        "xsssx",
        "xxxxx"],
    H: ["xsssx",
        "xsssx",
        "xxxxx",
        "xsssx",
        "xsssx"],
    I: ["xxxxx",
        "ssxss",
        "ssxss",
        "ssxss",
        "xxxxx"],
    J: ["xxxxx",
        "ssssx",
        "xxssx",
        "xsssx",
        "xxxxx"],
    K: ["xsssx",
        "xssxs",
        "xxxss",
        "xssxs",
        "xsssx"],
    L: ["xssss",
        "xssss",
        "xssss",
        "xssss",
        "xxxxx"],
    M: ["xxsxx",
        "xsxsx",
        "xsxsx",
        "xsssx",
        "xsssx"],
    N: ["xsssx",
        "xxssx",
        "xsxsx",
        "xssxx",
        "xsssx"],
    O: ["xxxxx",
        "xsssx",
        "xsssx",
        "xsssx",
        "xxxxx"],
    P: ["xxxxs",
        "xsssx",
        "xxxxs",
        "xssss",
        "xssss"],
    Q: ["sxxxs",
        "xsssx",
        "xsssx",
        "xxxxx",
        "ssssx"],
    R: ["sxxxs",
        "xsssx",
        "xxxxs",
        "xssxs",
        "xsssx"],
    S: ["xxxxs",
        "xssss",
        "sxxxs",
        "ssssx",
        "xxxxx"],
    T: ["xxxxx",
        "ssxss",
        "ssxss",
        "ssxss",
        "ssxss"],
    U: ["xsssx",
        "xsssx",
        "xsssx",
        "xsssx",
        "sxxxs"],
    V: ["xsssx",
        "xsssx",
        "xsssx",
        "sxsxs",
        "ssxss"],
    W: ["xsssx",
        "xsssx",
        "xsssx",
        "xsxsx",
        "sxsxs"],
    X: ["xsssx",
        "sxsxs",
        "ssxss",
        "sxsxs",
        "xsssx"],
    Y: ["xsssx",
        "sxsxs",
        "ssxss",
        "ssxss",
        "ssxss"],
    Z: ["xxxxx",
        "sssxs",
        "ssxss",
        "sxsss",
        "xxxxx"],
    // Punctuation
    '_': ["sss",
        "sss",
        "sss",
        "sss",
        "sss"],
    '!': ["ssxss",
        "ssxss",
        "ssxss",
        "sssss",
        "ssxss"]
};

module.exports = letterMap;